# Site settings
title: Lars Blog
email: al8bright@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ubuntu OS, Ruby On Rails, Perl Catalyst, Postgresql, Mysql
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://al8bright.github.io" # the base hostname & protocol for your site
twitter_username: al8bright
github_username:  al8bright

# Build settings
markdown: redcarpet
